In [82]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import BatchNormalization

from keras.utils import np_utils

In [83]:
df = pd.read_csv('data/VTOUTP16.TXT', low_memory=False)
df.head()

hnum2  ATYPE asour  intage TXTZIP sex  dstat  PPAY    CHRGS     DX1  \
0     11      3     4      13    050   2      5     1  3409.85    L600   
1     11      3     4      11    050   2      5     7  1837.65  Z86010   
2     11      3     4      12    037   2      5     1  1102.65   Z1211   
3     11      3     4      10    050   1      5     7  1102.70   Z1211   
4     11      3     4      13    051   2      5     7  1837.65   Z1211   

     ...     BTYPE ERFLAG cah vtres OBSFLAG AFLAG Uniq ADMID_QTR DISCD_QTR  \
0    ...       131      0   1     1       0     1    3         1         1   
1    ...       131      0   1     1       0     1   54         1         1   
2    ...       131      0   1     3       0     1   85         1         1   
3    ...       131      0   1     1       0     1   87         1         1   
4    ...       131      0   1     1       0     1   93         1         1   

  CHRGS_HCIA  
0    3409.85  
1    1837.65  
2    1102.65  
3    1102.70  
4    1837.65  

[5 rows x 70 columns]

In [84]:
# clean data
## only use the procedure columns
df.drop(df.columns[0:29],axis=1,inplace=True) # delete everything before PX columns
df.drop(df.columns[11:],axis=1,inplace=True) # delete everything after the first 10 PX columns (the last 10 PX columns are empty)

## delete columns where no procedurestook place
df = df[df.PX1 != ' ']
df.head()

PX1      PX2      PX3      PX4      PX5      PX6      PX7 PX8 PX9  \
535    0HRV37Z  0UT2FZZ  0JDM3ZZ  0JDL3ZZ  0WQF0ZZ  0UT7FZZ  3E1P38Z           
6226   09Q10ZZ  0JQ00ZZ  0HQ1XZZ  0CQ0XZZ                                      
8661   B246ZZZ                                                                 
12438  30233N1                                                                 
13316  0DB68ZX  0D748ZZ                                                        

      PX10 PX11  
535              
6226             
8661             
12438            
13316

In [85]:
# clean up data
## replace spaces with 0
df.replace([' '], [0], inplace=True)

In [86]:
## replace all ICD-9 codes with ints in the PX columns
icd9codes_dict = {}
replacement = 0
for i in range (1,12):
    current_column = f'PX{i}'
    for icd9code in df[current_column]:
        if icd9code not in icd9codes_dict.keys():
            icd9codes_dict[icd9code] = replacement
            replacement += 1

for i in range (1,12):
    current_column = f'PX{i}'
    df[current_column] = df[current_column].map(icd9codes_dict)
    df[current_column] = pd.to_numeric(df[current_column])

In [87]:
# set features and targets
y = [] ## y = next procedure
X = [] ## X = current procedure
for row in df.values:
    for i in range(0, len(row)):
        if(row[i] == icd9codes_dict[0]): # if value is empty (equivalent of zero)
            y.append(row[i-1]) # y is the value of the column before the one with the zero value
            X.append(row[i-2]) # X is the value of the column before y
            break # go to next row

In [92]:
# check first row
print("full row:\n{0}\n".format(df.iloc[0]))
print("X: {0}".format(X[0]))
print("y: {0}".format(y[0]))

full row:
PX1        0
PX2     1347
PX3     1691
PX4     1813
PX5       12
PX6     1417
PX7     1896
PX8     1348
PX9     1348
PX10    1348
PX11    1348
Name: 535, dtype: int64

X: 1417
y: 1896


In [93]:
X = np.asarray(X)
y = np.asarray(y)

In [94]:
# split into training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [95]:
print(X_train.shape)

(16442,)


In [96]:
# One-hot encoding
y_train = np_utils.to_categorical(y_train)

In [97]:
print(y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [125]:
# setup model
## parameters
model = Sequential()
dropoutrate = 0.2
batchsize = 1024
epochs = 1000
inputdim = 1
adam = keras.optimizers.Adam() # Adam optimizer

model.add(Dense(100, input_dim=inputdim, kernel_initializer='uniform',activation='relu'))
model.add(Dense(100, kernel_initializer='uniform',activation='relu'))
model.add(Dense(1911, activation='softmax'))

In [126]:
model.compile(loss=keras.losses.categorical_crossentropy,optimizer=adam,metrics=['accuracy'])

In [127]:
history = model.fit(X_train, y_train, epochs=epochs,validation_split=0.3, batch_size=batchsize,verbose=1)

Train on 11509 samples, validate on 4933 samples
Epoch 1/1000
11509/11509 [==============================] - 9s 763us/step - loss: 7.1419 - acc: 0.0319 - val_loss: 6.4854 - val_acc: 0.0701
Epoch 2/1000
11509/11509 [==============================] - 5s 455us/step - loss: 6.3019 - acc: 0.0591 - val_loss: 6.2466 - val_acc: 0.0762
Epoch 3/1000
11509/11509 [==============================] - 5s 447us/step - loss: 6.1527 - acc: 0.0735 - val_loss: 6.2497 - val_acc: 0.0669
Epoch 4/1000
11509/11509 [==============================] - 5s 461us/step - loss: 6.1105 - acc: 0.0738 - val_loss: 6.2589 - val_acc: 0.0693
Epoch 5/1000
11509/11509 [==============================] - 5s 447us/step - loss: 6.0859 - acc: 0.0726 - val_loss: 6.2566 - val_acc: 0.0780
Epoch 6/1000
11509/11509 [==============================] - 5s 449us/step - loss: 6.0637 - acc: 0.0726 - val_loss: 6.2633 - val_acc: 0.0774
Epoch 7/1000
11509/11509 [==============================] - 5s 452us/step - loss: 6.0442 - acc: 0.0708 - val_lo

Epoch 59/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.6848 - acc: 0.0990 - val_loss: 5.0993 - val_acc: 0.1001
Epoch 60/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.6806 - acc: 0.0989 - val_loss: 5.1025 - val_acc: 0.1001
Epoch 61/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.6750 - acc: 0.0990 - val_loss: 5.1002 - val_acc: 0.1001
Epoch 62/1000
11509/11509 [==============================] - 6s 497us/step - loss: 4.6723 - acc: 0.0990 - val_loss: 5.0937 - val_acc: 0.1001
Epoch 63/1000
11509/11509 [==============================] - 6s 493us/step - loss: 4.6712 - acc: 0.0990 - val_loss: 5.0979 - val_acc: 0.1003
Epoch 64/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.6675 - acc: 0.0991 - val_loss: 5.0914 - val_acc: 0.1001
Epoch 65/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.6659 - acc: 0.0994 - val_loss: 5.0930 - val_acc: 0.1003
Epoch 66/1000

Epoch 117/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.5702 - acc: 0.1117 - val_loss: 5.0522 - val_acc: 0.1101
Epoch 118/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.5678 - acc: 0.1075 - val_loss: 5.0555 - val_acc: 0.1012
Epoch 119/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.5754 - acc: 0.1038 - val_loss: 5.0812 - val_acc: 0.1003
Epoch 120/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.5819 - acc: 0.1037 - val_loss: 5.0534 - val_acc: 0.1010
Epoch 121/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.5712 - acc: 0.1050 - val_loss: 5.0649 - val_acc: 0.1143
Epoch 122/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.5762 - acc: 0.1044 - val_loss: 5.0501 - val_acc: 0.1083
Epoch 123/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.5616 - acc: 0.1066 - val_loss: 5.0489 - val_acc: 0.1095
Epoch 

Epoch 175/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.5467 - acc: 0.1037 - val_loss: 5.0628 - val_acc: 0.1091
Epoch 176/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.5330 - acc: 0.1039 - val_loss: 5.0344 - val_acc: 0.1133
Epoch 177/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.5240 - acc: 0.1074 - val_loss: 5.0318 - val_acc: 0.1233
Epoch 178/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.5111 - acc: 0.1093 - val_loss: 5.0335 - val_acc: 0.1095
Epoch 179/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.5041 - acc: 0.1088 - val_loss: 5.0392 - val_acc: 0.1113
Epoch 180/1000
11509/11509 [==============================] - 5s 449us/step - loss: 4.5100 - acc: 0.1097 - val_loss: 5.0376 - val_acc: 0.1097
Epoch 181/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.5013 - acc: 0.1115 - val_loss: 5.0576 - val_acc: 0.1101
Epoch 

Epoch 233/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.4596 - acc: 0.1210 - val_loss: 5.0445 - val_acc: 0.1174
Epoch 234/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.4655 - acc: 0.1168 - val_loss: 5.0325 - val_acc: 0.1360
Epoch 235/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.4619 - acc: 0.1155 - val_loss: 5.0332 - val_acc: 0.1340
Epoch 236/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.4622 - acc: 0.1203 - val_loss: 5.0348 - val_acc: 0.1194
Epoch 237/1000
11509/11509 [==============================] - 5s 457us/step - loss: 4.4627 - acc: 0.1140 - val_loss: 5.0404 - val_acc: 0.1137
Epoch 238/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.4579 - acc: 0.1220 - val_loss: 5.0358 - val_acc: 0.1164
Epoch 239/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.4544 - acc: 0.1162 - val_loss: 5.0376 - val_acc: 0.1135
Epoch 

Epoch 291/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.4198 - acc: 0.1205 - val_loss: 5.0443 - val_acc: 0.1141
Epoch 292/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.4179 - acc: 0.1191 - val_loss: 5.0360 - val_acc: 0.1206
Epoch 293/1000
11509/11509 [==============================] - 5s 449us/step - loss: 4.4173 - acc: 0.1188 - val_loss: 5.0374 - val_acc: 0.1220
Epoch 294/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.4152 - acc: 0.1208 - val_loss: 5.0313 - val_acc: 0.1257
Epoch 295/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.4193 - acc: 0.1233 - val_loss: 5.0366 - val_acc: 0.1224
Epoch 296/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.4141 - acc: 0.1214 - val_loss: 5.0327 - val_acc: 0.1243
Epoch 297/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.4116 - acc: 0.1225 - val_loss: 5.0311 - val_acc: 0.1206
Epoch 

Epoch 349/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.3781 - acc: 0.1227 - val_loss: 5.0267 - val_acc: 0.1239
Epoch 350/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3808 - acc: 0.1262 - val_loss: 5.0321 - val_acc: 0.1368
Epoch 351/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3788 - acc: 0.1281 - val_loss: 5.0415 - val_acc: 0.1393
Epoch 352/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.3737 - acc: 0.1325 - val_loss: 5.0490 - val_acc: 0.1316
Epoch 353/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3891 - acc: 0.1224 - val_loss: 5.0402 - val_acc: 0.1166
Epoch 354/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.3784 - acc: 0.1317 - val_loss: 5.0387 - val_acc: 0.1119
Epoch 355/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.3797 - acc: 0.1287 - val_loss: 5.0398 - val_acc: 0.1397
Epoch 

Epoch 407/1000
11509/11509 [==============================] - 5s 449us/step - loss: 4.3525 - acc: 0.1347 - val_loss: 5.0410 - val_acc: 0.1241
Epoch 408/1000
11509/11509 [==============================] - 5s 449us/step - loss: 4.3539 - acc: 0.1256 - val_loss: 5.0161 - val_acc: 0.1251
Epoch 409/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.3567 - acc: 0.1271 - val_loss: 5.0300 - val_acc: 0.1239
Epoch 410/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3524 - acc: 0.1256 - val_loss: 5.0207 - val_acc: 0.1241
Epoch 411/1000
11509/11509 [==============================] - 5s 462us/step - loss: 4.3474 - acc: 0.1250 - val_loss: 5.0218 - val_acc: 0.1255
Epoch 412/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.3444 - acc: 0.1295 - val_loss: 5.0148 - val_acc: 0.1230
Epoch 413/1000
11509/11509 [==============================] - 5s 473us/step - loss: 4.3380 - acc: 0.1322 - val_loss: 5.0239 - val_acc: 0.1308
Epoch 

Epoch 465/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.3255 - acc: 0.1282 - val_loss: 5.0115 - val_acc: 0.1303
Epoch 466/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.3252 - acc: 0.1319 - val_loss: 5.0318 - val_acc: 0.1166
Epoch 467/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3306 - acc: 0.1278 - val_loss: 5.0721 - val_acc: 0.1297
Epoch 468/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.3508 - acc: 0.1261 - val_loss: 5.1054 - val_acc: 0.1155
Epoch 469/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3660 - acc: 0.1275 - val_loss: 5.0291 - val_acc: 0.1263
Epoch 470/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3535 - acc: 0.1247 - val_loss: 5.2084 - val_acc: 0.1170
Epoch 471/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.8935 - acc: 0.0918 - val_loss: 5.3003 - val_acc: 0.0993
Epoch 

Epoch 523/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.3121 - acc: 0.1271 - val_loss: 5.0127 - val_acc: 0.1243
Epoch 524/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.3119 - acc: 0.1302 - val_loss: 5.0102 - val_acc: 0.1297
Epoch 525/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.3133 - acc: 0.1301 - val_loss: 5.0081 - val_acc: 0.1297
Epoch 526/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.3114 - acc: 0.1262 - val_loss: 5.0256 - val_acc: 0.1334
Epoch 527/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.3150 - acc: 0.1276 - val_loss: 5.0175 - val_acc: 0.1233
Epoch 528/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.3187 - acc: 0.1319 - val_loss: 5.0174 - val_acc: 0.1383
Epoch 529/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.3119 - acc: 0.1335 - val_loss: 5.0152 - val_acc: 0.1233
Epoch 

Epoch 581/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.3414 - acc: 0.1256 - val_loss: 5.3838 - val_acc: 0.0616
Epoch 582/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.4910 - acc: 0.1152 - val_loss: 5.0553 - val_acc: 0.1200
Epoch 583/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.3438 - acc: 0.1294 - val_loss: 5.0166 - val_acc: 0.1297
Epoch 584/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.3141 - acc: 0.1311 - val_loss: 5.0243 - val_acc: 0.1267
Epoch 585/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.3074 - acc: 0.1326 - val_loss: 5.0186 - val_acc: 0.1212
Epoch 586/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.3007 - acc: 0.1287 - val_loss: 5.0108 - val_acc: 0.1251
Epoch 587/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.2934 - acc: 0.1302 - val_loss: 5.0100 - val_acc: 0.1237
Epoch 

Epoch 639/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.2947 - acc: 0.1415 - val_loss: 5.0396 - val_acc: 0.1413
Epoch 640/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.2975 - acc: 0.1331 - val_loss: 5.0011 - val_acc: 0.1320
Epoch 641/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.2819 - acc: 0.1351 - val_loss: 5.0166 - val_acc: 0.1391
Epoch 642/1000
11509/11509 [==============================] - 5s 447us/step - loss: 4.2824 - acc: 0.1317 - val_loss: 5.0011 - val_acc: 0.1376
Epoch 643/1000
11509/11509 [==============================] - 5s 459us/step - loss: 4.2735 - acc: 0.1403 - val_loss: 5.0162 - val_acc: 0.1239
Epoch 644/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2776 - acc: 0.1402 - val_loss: 5.0054 - val_acc: 0.1370
Epoch 645/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2757 - acc: 0.1351 - val_loss: 4.9991 - val_acc: 0.1445
Epoch 

Epoch 697/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.2827 - acc: 0.1386 - val_loss: 4.9994 - val_acc: 0.1383
Epoch 698/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.2638 - acc: 0.1446 - val_loss: 4.9982 - val_acc: 0.1458
Epoch 699/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.2661 - acc: 0.1417 - val_loss: 4.9980 - val_acc: 0.1453
Epoch 700/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.2611 - acc: 0.1398 - val_loss: 4.9924 - val_acc: 0.1409
Epoch 701/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.2603 - acc: 0.1408 - val_loss: 5.0072 - val_acc: 0.1427
Epoch 702/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.2686 - acc: 0.1448 - val_loss: 5.0182 - val_acc: 0.1419
Epoch 703/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.2733 - acc: 0.1419 - val_loss: 4.9904 - val_acc: 0.1445
Epoch 

Epoch 755/1000
11509/11509 [==============================] - 5s 476us/step - loss: 4.2904 - acc: 0.1401 - val_loss: 4.9907 - val_acc: 0.1380
Epoch 756/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2457 - acc: 0.1444 - val_loss: 4.9954 - val_acc: 0.1417
Epoch 757/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.2425 - acc: 0.1481 - val_loss: 4.9945 - val_acc: 0.1492
Epoch 758/1000
11509/11509 [==============================] - 5s 459us/step - loss: 4.2413 - acc: 0.1468 - val_loss: 4.9918 - val_acc: 0.1389
Epoch 759/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.2365 - acc: 0.1470 - val_loss: 4.9939 - val_acc: 0.1419
Epoch 760/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2394 - acc: 0.1422 - val_loss: 4.9972 - val_acc: 0.1348
Epoch 761/1000
11509/11509 [==============================] - 5s 449us/step - loss: 4.2456 - acc: 0.1454 - val_loss: 4.9962 - val_acc: 0.1441
Epoch 

Epoch 813/1000
11509/11509 [==============================] - 5s 457us/step - loss: 4.2231 - acc: 0.1497 - val_loss: 4.9853 - val_acc: 0.1350
Epoch 814/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.2250 - acc: 0.1475 - val_loss: 4.9864 - val_acc: 0.1464
Epoch 815/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2236 - acc: 0.1501 - val_loss: 5.0044 - val_acc: 0.1366
Epoch 816/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.2730 - acc: 0.1456 - val_loss: 5.0289 - val_acc: 0.1364
Epoch 817/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2479 - acc: 0.1421 - val_loss: 4.9812 - val_acc: 0.1433
Epoch 818/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2260 - acc: 0.1474 - val_loss: 4.9907 - val_acc: 0.1466
Epoch 819/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2293 - acc: 0.1459 - val_loss: 4.9866 - val_acc: 0.1405
Epoch 

Epoch 871/1000
11509/11509 [==============================] - 5s 447us/step - loss: 4.2226 - acc: 0.1443 - val_loss: 4.9952 - val_acc: 0.1401
Epoch 872/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.2135 - acc: 0.1472 - val_loss: 4.9807 - val_acc: 0.1474
Epoch 873/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.2112 - acc: 0.1505 - val_loss: 4.9816 - val_acc: 0.1429
Epoch 874/1000
11509/11509 [==============================] - 5s 453us/step - loss: 4.2190 - acc: 0.1435 - val_loss: 4.9912 - val_acc: 0.1378
Epoch 875/1000
11509/11509 [==============================] - 5s 447us/step - loss: 4.2214 - acc: 0.1433 - val_loss: 4.9859 - val_acc: 0.1431
Epoch 876/1000
11509/11509 [==============================] - 5s 457us/step - loss: 4.2565 - acc: 0.1450 - val_loss: 4.9804 - val_acc: 0.1423
Epoch 877/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2171 - acc: 0.1444 - val_loss: 4.9775 - val_acc: 0.1429
Epoch 

Epoch 929/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2160 - acc: 0.1468 - val_loss: 4.9770 - val_acc: 0.1421
Epoch 930/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.2045 - acc: 0.1505 - val_loss: 4.9817 - val_acc: 0.1466
Epoch 931/1000
11509/11509 [==============================] - 5s 452us/step - loss: 4.2021 - acc: 0.1494 - val_loss: 4.9897 - val_acc: 0.1387
Epoch 932/1000
11509/11509 [==============================] - 5s 451us/step - loss: 4.2032 - acc: 0.1478 - val_loss: 5.0076 - val_acc: 0.1376
Epoch 933/1000
11509/11509 [==============================] - 5s 448us/step - loss: 4.2141 - acc: 0.1488 - val_loss: 5.0009 - val_acc: 0.1399
Epoch 934/1000
11509/11509 [==============================] - 5s 466us/step - loss: 4.2086 - acc: 0.1470 - val_loss: 4.9926 - val_acc: 0.1237
Epoch 935/1000
11509/11509 [==============================] - 5s 456us/step - loss: 4.2081 - acc: 0.1461 - val_loss: 4.9793 - val_acc: 0.1421
Epoch 

Epoch 987/1000
11509/11509 [==============================] - 5s 459us/step - loss: 4.2084 - acc: 0.1481 - val_loss: 5.0714 - val_acc: 0.1180
Epoch 988/1000
11509/11509 [==============================] - 5s 458us/step - loss: 4.2502 - acc: 0.1415 - val_loss: 4.9958 - val_acc: 0.1372
Epoch 989/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2245 - acc: 0.1477 - val_loss: 4.9991 - val_acc: 0.1376
Epoch 990/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2153 - acc: 0.1450 - val_loss: 4.9833 - val_acc: 0.1449
Epoch 991/1000
11509/11509 [==============================] - 5s 455us/step - loss: 4.2092 - acc: 0.1488 - val_loss: 4.9812 - val_acc: 0.1419
Epoch 992/1000
11509/11509 [==============================] - 5s 450us/step - loss: 4.2051 - acc: 0.1488 - val_loss: 4.9900 - val_acc: 0.1376
Epoch 993/1000
11509/11509 [==============================] - 5s 454us/step - loss: 4.2081 - acc: 0.1427 - val_loss: 4.9920 - val_acc: 0.1500
Epoch 

In [128]:
# predict the number of days a person has to stay in the hospital
predictions = model.predict(X_test)

In [129]:
# compare prediction with real
n = 0
print("Predicted: {0} \tcertainty: {1}".format(predictions[n].argmax(axis=0), predictions[n][predictions[n].argmax(axis=0)]))
print("Real: {0}".format(list(y_test)[n]))

Predicted: 13 	certainty: 0.18232372403144836
Real: 20


In [130]:
# make list of all predictions
y_predicted = []
for i in range(0, len(predictions)):
    y_predicted.append(predictions[i].argmax(axis=0))

In [132]:
# convert ints back to ICD codes
icd_test = []
icd_predicted = []
for i in range(0, len(y_test)):
    for key,value in icd9codes_dict.items():
        # convert y_test number to ICD code
        if(value == list(y_test)[i]):
            icd_test.append(key)
        # convert predicted number to ICD code
        elif(value == y_predicted[i]):
            icd_predicted.append(key)

In [133]:
# compare prediction with real
n = 1
print("Predicted: {0}".format(icd_predicted[n]))
print("Real: {0}".format(icd_test[n]))

Predicted: 4A0971Z
Real: 3E0234Z


In [136]:
# save model for later use
# https://stackoverflow.com/questions/40396042/how-to-save-scikit-learn-keras-model-into-a-persistence-file-pickle-hd5-json-ya
model.save('model_procedure_next.h5')
# save ICD code for later use
#https://stackoverflow.com/questions/19201290/how-to-save-a-dictionary-to-a-file
np.save('icd_procedure.npy', icd9codes_dict) 